const scenarios = [
    "System Downtime: During a major software upgrade, the client's critical system goes down unexpectedly. How would you mitigate this risk?",
    "Data Migration Issues: Data corruption occurs during the migration process to a new ERP system. What steps would you take to control this risk?",
    "Compatibility Problems: The new software is found to be incompatible with the client's legacy systems. How would you address this issue?",
    "Performance Degradation: After an upgrade, the client's system performance slows down significantly. What measures would you implement to resolve this?",
    "Security Vulnerabilities: The newly implemented software exposes security vulnerabilities. How would you mitigate this risk?",
    "Integration Failures: Integration with a third-party CRM system fails. What actions would you take to control this risk?",
    "Software Bugs: Critical bugs are discovered in the newly deployed software. How would you handle this situation?",
    "Network Issues: Network connectivity problems disrupt the implementation process. What steps would you take to mitigate this risk?",
    "Insufficient Testing: Inadequate testing leads to undetected issues in production. How would you ensure thorough testing?",
    "Backup Failures: Backup systems fail during a critical upgrade. How would you mitigate this risk?",
    "Key Personnel Departure: A key team member leaves the project mid-way. How would you manage this risk?",
    "Team Conflicts: Disagreements among team members affect project progress. How would you resolve this issue?",
    "Skill Gaps: The team lacks necessary skills to handle specific tasks. How would you address this gap?",
    "Resource Reallocation: Team members are reassigned to other projects, causing delays. How would you mitigate this risk?",
    "Training Needs: New team members require extensive training to get up to speed. How would you manage this?",
    "Leadership Changes: Changes in project leadership lead to shifts in project direction. How would you control this risk?",
    "Employee Burnout: High workload leads to burnout and decreased productivity. How would you mitigate this risk?",
    "Remote Work Challenges: Coordination issues arise with remote team members. How would you address this?",
    "Communication Breakdowns: Miscommunication between team members causes errors. How would you resolve this issue?",
    "Recruitment Delays: Delays in hiring new team members impact project timelines. How would you manage this risk?",
    "Budget Overruns: Project costs exceed the allocated budget. How would you control this risk?",
    "Funding Cuts: Unexpected cuts in funding lead to resource constraints. How would you mitigate this risk?",
    "Cost Estimation Errors: Initial cost estimates are significantly off. How would you address this issue?",
    "Vendor Price Increases: Vendors increase prices unexpectedly. How would you manage this risk?",
    "Unforeseen Expenses: Unplanned expenses arise during the project. How would you control this risk?",
    "Contract Disputes: Disputes with vendors or clients over contract terms. How would you resolve this issue?",
    "Delayed Payments: Delays in client payments affect cash flow. How would you mitigate this risk?",
    "Resource Allocation: Misallocation of budget resources leads to shortages. How would you manage this risk?",
    "Financial Audits: Financial audits uncover discrepancies in project spending. How would you address this issue?",
    "Cost-Saving Measures: Implementing cost-saving measures impacts project quality. How would you control this risk?",
    "Scope Creep: Clients continuously add new requirements, expanding project scope. How would you manage this risk?",
    "Client Approval Delays: Delays in client approvals hold up project progress. How would you mitigate this risk?",
    "Client Miscommunication: Misunderstandings with clients about project deliverables. How would you resolve this issue?",
    "Client Resistance: Clients resist changes proposed during the implementation. How would you manage this risk?",
    "Stakeholder Conflicts: Conflicts among client stakeholders affect decision-making. How would you address this issue?",
    "Client Training Needs: Clients require extensive training on new systems. How would you manage this?",
    "Client Data Privacy Concerns: Clients raise concerns about data privacy and security. How would you mitigate this risk?",
    "Client Infrastructure Limitations: Client’s existing infrastructure limits implementation options. How would you address this issue?",
    "Client Budget Constraints: Clients have limited budgets for the project. How would you manage this risk?",
    "Client Feedback: Negative client feedback requires project adjustments. How would you address this issue?",
    "Timeline Delays: Project timelines are delayed due to unforeseen issues. How would you manage this risk?",
    "Resource Shortages: Shortages of critical resources impact project progress. How would you mitigate this risk?",
    "Risk Management: Unanticipated risks materialize, affecting the project. How would you control this risk?",
    "Quality Assurance: Ensuring high-quality deliverables within tight deadlines. How would you manage this?",
    "Regulatory Compliance: Meeting regulatory requirements adds complexity. How would you address this issue?",
    "Change Management: Managing changes in project scope, timeline, or resources. How would you control this risk?",
    "Documentation Gaps: Incomplete or outdated project documentation. How would you address this issue?",
    "Stakeholder Engagement: Keeping stakeholders engaged and informed. How would you manage this?",
    "Project Prioritization: Balancing multiple high-priority projects simultaneously. How would you manage this risk?",
    "Performance Metrics: Tracking and reporting on project performance metrics. How would you ensure accuracy?",
  ];
  
  export default scenarios;
  